// automatically generated by the FlatBuffers compiler, do not modify

package Game.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GameState extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static GameState getRootAsGameState(ByteBuffer _bb) { return getRootAsGameState(_bb, new GameState()); }
  public static GameState getRootAsGameState(ByteBuffer _bb, GameState obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GameState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short field(int j) { int o = __offset(4); return o != 0 ? bb.getShort(__vector(o) + j * 2) : 0; }
  public int fieldLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ShortVector fieldVector() { return fieldVector(new ShortVector()); }
  public ShortVector fieldVector(ShortVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer fieldAsByteBuffer() { return __vector_as_bytebuffer(4, 2); }
  public ByteBuffer fieldInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 2); }
  public boolean won() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int steps() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int maxSteps() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int width() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int height() { int o = __offset(14); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createGameState(FlatBufferBuilder builder,
      int fieldOffset,
      boolean won,
      int steps,
      int maxSteps,
      int width,
      int height) {
    builder.startTable(6);
    GameState.addHeight(builder, height);
    GameState.addWidth(builder, width);
    GameState.addMaxSteps(builder, maxSteps);
    GameState.addSteps(builder, steps);
    GameState.addField(builder, fieldOffset);
    GameState.addWon(builder, won);
    return GameState.endGameState(builder);
  }

  public static void startGameState(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addField(FlatBufferBuilder builder, int fieldOffset) { builder.addOffset(0, fieldOffset, 0); }
  public static int createFieldVector(FlatBufferBuilder builder, short[] data) { builder.startVector(2, data.length, 2); for (int i = data.length - 1; i >= 0; i--) builder.addShort(data[i]); return builder.endVector(); }
  public static void startFieldVector(FlatBufferBuilder builder, int numElems) { builder.startVector(2, numElems, 2); }
  public static void addWon(FlatBufferBuilder builder, boolean won) { builder.addBoolean(1, won, false); }
  public static void addSteps(FlatBufferBuilder builder, int steps) { builder.addInt(2, steps, 0); }
  public static void addMaxSteps(FlatBufferBuilder builder, int maxSteps) { builder.addInt(3, maxSteps, 0); }
  public static void addWidth(FlatBufferBuilder builder, int width) { builder.addInt(4, width, 0); }
  public static void addHeight(FlatBufferBuilder builder, int height) { builder.addInt(5, height, 0); }
  public static int endGameState(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishGameStateBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedGameStateBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GameState get(int j) { return get(new GameState(), j); }
    public GameState get(GameState obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public GameStateT unpack() {
    GameStateT _o = new GameStateT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(GameStateT _o) {
    short[] _oField = new short[fieldLength()];
    for (int _j = 0; _j < fieldLength(); ++_j) {_oField[_j] = field(_j);}
    _o.setField(_oField);
    boolean _oWon = won();
    _o.setWon(_oWon);
    int _oSteps = steps();
    _o.setSteps(_oSteps);
    int _oMaxSteps = maxSteps();
    _o.setMaxSteps(_oMaxSteps);
    int _oWidth = width();
    _o.setWidth(_oWidth);
    int _oHeight = height();
    _o.setHeight(_oHeight);
  }
  public static int pack(FlatBufferBuilder builder, GameStateT _o) {
    if (_o == null) return 0;
    int _field = 0;
    if (_o.getField() != null) {
      _field = createFieldVector(builder, _o.getField());
    }
    return createGameState(
      builder,
      _field,
      _o.getWon(),
      _o.getSteps(),
      _o.getMaxSteps(),
      _o.getWidth(),
      _o.getHeight());
  }
}

