// automatically generated by the FlatBuffers compiler, do not modify

package Game.model;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class ScoreT {
  private int player;
  private int steps;
  private boolean won;
  private int comboScore;

  public int getPlayer() { return player; }

  public void setPlayer(int player) { this.player = player; }

  public int getSteps() { return steps; }

  public void setSteps(int steps) { this.steps = steps; }

  public boolean getWon() { return won; }

  public void setWon(boolean won) { this.won = won; }

  public int getComboScore() { return comboScore; }

  public void setComboScore(int comboScore) { this.comboScore = comboScore; }


  public ScoreT() {
    this.player = 0;
    this.steps = 0;
    this.won = false;
    this.comboScore = 0;
  }
}

